---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: Install Docker (CentOS)
    dnf:
      name:
        - docker
      state: latest
    when: ansible_distribution == "CentOS"




